### ISSUE TITLE
[nrc.en.mtnt] More contractions in suggestions

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/lexical-models#143]
A user suggested that more contractions are given in the suggestion banner of the EuroLatin (SIL) keyboard.

**Comment by darcywong00** [comment]
The lexical-model we're using for English is nrc.en.mtnt/ and the wordlist is mtnt.tsv

I do note the contractions in the wordlist use "left single quotation mark" `‘` instead of "apostrophe" `'`

**Comment by DavidLRowe** [comment]
I agree that U+2018 "left single quotation mark" is not the right character. 

If the lexical model uses U+0027 "apostrophe", what will happen when this model is used with a keyboard that changes apostrophe (U+0027) to "right single quotation mark" (U+2019). If I type "did" and then pick "didn't" from the list, it seems as though I'll get the U+0027 from the .tsv file rather than the U+2019 that the keyboard would generate. OTOH if I type "didn'" and the keyboard changes the U+0027 to U+2019, it seems it will no longer offer me "didn't" as a possibility because the apostrophe no longer matches. 

But there's lots about this process that I don't understand!

**Comment by darcywong00** [comment]
With a context of "were", I get 3 suggestions:
"were" (frequency 5309)
"weren't" (frequency 385)
"werent" (frequency 16)

"we're" has a frequency of 927 so I would expect it to appear

I wonder if we should also scrub the following (typos and symbols) from the wordlist:
werent	16
hasnt   23
wouldnt 80
couldnt 37
shouldnt  39
dont 977
hes  116
arent 73

$	1898
√	(square root, frequency 19)
______	6
▢	9
ಠ_ಠ	9

**Comment by DavidLRowe** [comment]
@darcywong00 I agree that there are typos and symbols that should be removed.

What about proper names (Danae, Kristin, Derrick, etc.)? Or Catan?!

What about 32GB and 6g?

The question is who would like to undertake this effort?

**Comment by jahorton** [comment]
> I agree that U+2018 "left single quotation mark" is not the right character.
> 
> If the lexical model uses U+0027 "apostrophe", what will happen when this model is used with a keyboard that changes apostrophe (U+0027) to "right single quotation mark" (U+2019). If I type "did" and then pick "didn't" from the list, it seems as though I'll get the U+0027 from the .tsv file rather than the U+2019 that the keyboard would generate. OTOH if I type "didn'" and the keyboard changes the U+0027 to U+2019, it seems it will no longer offer me "didn't" as a possibility because the apostrophe no longer matches.
> 
> But there's lots about this process that I don't understand!

We can always solve that hypothetical case by modifying https://github.com/keymanapp/keyman/blob/master/developer/js/source/lexical-model-compiler/model-defaults.ts.  In particular...

https://github.com/keymanapp/keyman/blob/d691c149ea14a9de9e5ff7c471b9e6ef118801eb/developer/js/source/lexical-model-compiler/model-defaults.ts#L22-L27

If we add something here that replaces U+2018 with U+0027, that'd be the resolution.  (It'd also resolve things in the other direction.)  The one thing is that this'd only affect future versions of Keyman, rather than fixing this for all versions.  We can do _that_ by implementing a similar change within this model's code as well; I know how to set that up should we wish to do so.

**Comment by mcdurdin** [comment]
> The one thing is that this'd only affect future versions of Keyman, rather than fixing this for all versions.

I don't think we need back-version resolution of issues like this. Fix it going forward.

**Comment by darcywong00** [comment]
TODO that still remains:

- [ ] I do note the contractions in the wordlist use "left single quotation mark" ‘ instead of "apostrophe" '

**Comment by mcdurdin** [comment]
@darcywong00 can we follow up on this TODO?

**Comment by DavidLRowe** [comment]
@darcywong00 It seems that most items here have been addressed, or else listed on issue #178 . Perhaps this issue could be closed?

**Comment by darcywong00** [comment]
I think this still needs to remain open for @jahorton to confirm this is resolved:
> With a context of "were", I get 3 suggestions:
"were" (frequency 5309)
"weren't" (frequency 385)
"werent" (frequency 16)
>
>"we're" has a frequency of 927 so I would expect it to appear

On my alpha build of Keyman for Android, I'm still not getting "we're" as a suggestion.

**Comment by mcdurdin** [comment]
Closing as mostly fixed, remaining work in #229.
